CREATE TABLE SONG (

  ARTISTID         VARCHAR(50),
  AVAILABLEMARKETS VARCHAR(2),
  DISC_NUM          INT,
  DURATION_MS       INT,
  EXPLICIT         BOOLEAN,
  EXTERNALURL      VARCHAR(2083),
  HREF             VARCHAR(50),
  ID               VARCHAR(50),
  ISPLAYABLE       BOOLEAN,
  LINKEDFROM       VARCHAR(2083),
  NAME             VARCHAR(100),
  PREVIEWURL       VARCHAR(2083),
  TRACK_NUMBER      INT,
  POPULARITY       INT,
  URI              VARCHAR(2083)

);