CREATE TABLE ARTIST (

  EXTERNALURL VARCHAR(2083),
  HREF        VARCHAR(2083),
  ID          VARCHAR(50),
  NAME        VARCHAR(100),
  TYPE        VARCHAR(6),
  URI         VARCHAR(2023),
  FOLLOWERS   INT,
  POPULARITY  INT

);