CREATE TABLE "USER" (

  URI            VARCHAR(2083),
  DISPLAY_NAME    VARCHAR(100),
  EXTERNAL_URL   VARCHAR(2083),
  NUM_OF_FOLLOWERS INT,
  HREF           VARCHAR(50),
  ID             VARCHAR(100),
  IMAGES         VARCHAR(2083)

);