CREATE TABLE PLAYLIST (

  URI    VARCHAR(2083),
  EXTERNALURL    VARCHAR(2083),
  NUMOFFOLLOWERS INT,
  HREF           VARCHAR(50),
  ID             VARCHAR(100),
  IMAGES         VARCHAR(2083),
  NAME           VARCHAR(100),
  OWNER          VARCHAR(100),
  SNAPSHOTID     VARCHAR(100),
  TRACKS         VARCHAR(100)

);